# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcin/git.devel.marcin/qt/StanowiskoChemiczne

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcin/git.devel.marcin/qt/StanowiskoChemiczne

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcin/git.devel.marcin/qt/StanowiskoChemiczne/CMakeFiles /home/marcin/git.devel.marcin/qt/StanowiskoChemiczne/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcin/git.devel.marcin/qt/StanowiskoChemiczne/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StanowiskoChemiczne

# Build rule for target.
StanowiskoChemiczne: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StanowiskoChemiczne
.PHONY : StanowiskoChemiczne

# fast build rule for target.
StanowiskoChemiczne/fast:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/build
.PHONY : StanowiskoChemiczne/fast

#=============================================================================
# Target rules for targets named StanowiskoChemiczne_autogen

# Build rule for target.
StanowiskoChemiczne_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StanowiskoChemiczne_autogen
.PHONY : StanowiskoChemiczne_autogen

# fast build rule for target.
StanowiskoChemiczne_autogen/fast:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne_autogen.dir/build.make CMakeFiles/StanowiskoChemiczne_autogen.dir/build
.PHONY : StanowiskoChemiczne_autogen/fast

StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.o: StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.o

.PHONY : StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.o

# target to build an object file
StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.o
.PHONY : StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.o

StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.i: StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.i

.PHONY : StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.i

# target to preprocess a source file
StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.i
.PHONY : StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.i

StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.s: StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.s

.PHONY : StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.s

# target to generate assembly for a file
StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.s
.PHONY : StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.cpp.s

StanowiskoChemiczne_autogen/mocs_compilation.o: StanowiskoChemiczne_autogen/mocs_compilation.cpp.o

.PHONY : StanowiskoChemiczne_autogen/mocs_compilation.o

# target to build an object file
StanowiskoChemiczne_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/StanowiskoChemiczne_autogen/mocs_compilation.cpp.o
.PHONY : StanowiskoChemiczne_autogen/mocs_compilation.cpp.o

StanowiskoChemiczne_autogen/mocs_compilation.i: StanowiskoChemiczne_autogen/mocs_compilation.cpp.i

.PHONY : StanowiskoChemiczne_autogen/mocs_compilation.i

# target to preprocess a source file
StanowiskoChemiczne_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/StanowiskoChemiczne_autogen/mocs_compilation.cpp.i
.PHONY : StanowiskoChemiczne_autogen/mocs_compilation.cpp.i

StanowiskoChemiczne_autogen/mocs_compilation.s: StanowiskoChemiczne_autogen/mocs_compilation.cpp.s

.PHONY : StanowiskoChemiczne_autogen/mocs_compilation.s

# target to generate assembly for a file
StanowiskoChemiczne_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/StanowiskoChemiczne_autogen/mocs_compilation.cpp.s
.PHONY : StanowiskoChemiczne_autogen/mocs_compilation.cpp.s

glowneokno.o: glowneokno.cpp.o

.PHONY : glowneokno.o

# target to build an object file
glowneokno.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/glowneokno.cpp.o
.PHONY : glowneokno.cpp.o

glowneokno.i: glowneokno.cpp.i

.PHONY : glowneokno.i

# target to preprocess a source file
glowneokno.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/glowneokno.cpp.i
.PHONY : glowneokno.cpp.i

glowneokno.s: glowneokno.cpp.s

.PHONY : glowneokno.s

# target to generate assembly for a file
glowneokno.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/glowneokno.cpp.s
.PHONY : glowneokno.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

oknoczujnikow.o: oknoczujnikow.cpp.o

.PHONY : oknoczujnikow.o

# target to build an object file
oknoczujnikow.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/oknoczujnikow.cpp.o
.PHONY : oknoczujnikow.cpp.o

oknoczujnikow.i: oknoczujnikow.cpp.i

.PHONY : oknoczujnikow.i

# target to preprocess a source file
oknoczujnikow.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/oknoczujnikow.cpp.i
.PHONY : oknoczujnikow.cpp.i

oknoczujnikow.s: oknoczujnikow.cpp.s

.PHONY : oknoczujnikow.s

# target to generate assembly for a file
oknoczujnikow.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/oknoczujnikow.cpp.s
.PHONY : oknoczujnikow.cpp.s

oknostatusowe.o: oknostatusowe.cpp.o

.PHONY : oknostatusowe.o

# target to build an object file
oknostatusowe.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/oknostatusowe.cpp.o
.PHONY : oknostatusowe.cpp.o

oknostatusowe.i: oknostatusowe.cpp.i

.PHONY : oknostatusowe.i

# target to preprocess a source file
oknostatusowe.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/oknostatusowe.cpp.i
.PHONY : oknostatusowe.cpp.i

oknostatusowe.s: oknostatusowe.cpp.s

.PHONY : oknostatusowe.s

# target to generate assembly for a file
oknostatusowe.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/oknostatusowe.cpp.s
.PHONY : oknostatusowe.cpp.s

stanczujnika.o: stanczujnika.cpp.o

.PHONY : stanczujnika.o

# target to build an object file
stanczujnika.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/stanczujnika.cpp.o
.PHONY : stanczujnika.cpp.o

stanczujnika.i: stanczujnika.cpp.i

.PHONY : stanczujnika.i

# target to preprocess a source file
stanczujnika.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/stanczujnika.cpp.i
.PHONY : stanczujnika.cpp.i

stanczujnika.s: stanczujnika.cpp.s

.PHONY : stanczujnika.s

# target to generate assembly for a file
stanczujnika.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/stanczujnika.cpp.s
.PHONY : stanczujnika.cpp.s

ustawieniadozownikaokno.o: ustawieniadozownikaokno.cpp.o

.PHONY : ustawieniadozownikaokno.o

# target to build an object file
ustawieniadozownikaokno.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/ustawieniadozownikaokno.cpp.o
.PHONY : ustawieniadozownikaokno.cpp.o

ustawieniadozownikaokno.i: ustawieniadozownikaokno.cpp.i

.PHONY : ustawieniadozownikaokno.i

# target to preprocess a source file
ustawieniadozownikaokno.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/ustawieniadozownikaokno.cpp.i
.PHONY : ustawieniadozownikaokno.cpp.i

ustawieniadozownikaokno.s: ustawieniadozownikaokno.cpp.s

.PHONY : ustawieniadozownikaokno.s

# target to generate assembly for a file
ustawieniadozownikaokno.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/ustawieniadozownikaokno.cpp.s
.PHONY : ustawieniadozownikaokno.cpp.s

ustawieniasygnalowokno.o: ustawieniasygnalowokno.cpp.o

.PHONY : ustawieniasygnalowokno.o

# target to build an object file
ustawieniasygnalowokno.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/ustawieniasygnalowokno.cpp.o
.PHONY : ustawieniasygnalowokno.cpp.o

ustawieniasygnalowokno.i: ustawieniasygnalowokno.cpp.i

.PHONY : ustawieniasygnalowokno.i

# target to preprocess a source file
ustawieniasygnalowokno.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/ustawieniasygnalowokno.cpp.i
.PHONY : ustawieniasygnalowokno.cpp.i

ustawieniasygnalowokno.s: ustawieniasygnalowokno.cpp.s

.PHONY : ustawieniasygnalowokno.s

# target to generate assembly for a file
ustawieniasygnalowokno.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/ustawieniasygnalowokno.cpp.s
.PHONY : ustawieniasygnalowokno.cpp.s

widokczujnika.o: widokczujnika.cpp.o

.PHONY : widokczujnika.o

# target to build an object file
widokczujnika.cpp.o:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/widokczujnika.cpp.o
.PHONY : widokczujnika.cpp.o

widokczujnika.i: widokczujnika.cpp.i

.PHONY : widokczujnika.i

# target to preprocess a source file
widokczujnika.cpp.i:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/widokczujnika.cpp.i
.PHONY : widokczujnika.cpp.i

widokczujnika.s: widokczujnika.cpp.s

.PHONY : widokczujnika.s

# target to generate assembly for a file
widokczujnika.cpp.s:
	$(MAKE) -f CMakeFiles/StanowiskoChemiczne.dir/build.make CMakeFiles/StanowiskoChemiczne.dir/widokczujnika.cpp.s
.PHONY : widokczujnika.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... StanowiskoChemiczne"
	@echo "... StanowiskoChemiczne_autogen"
	@echo "... StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.o"
	@echo "... StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.i"
	@echo "... StanowiskoChemiczne_autogen/EWIEGA46WW/qrc_ikony.s"
	@echo "... StanowiskoChemiczne_autogen/mocs_compilation.o"
	@echo "... StanowiskoChemiczne_autogen/mocs_compilation.i"
	@echo "... StanowiskoChemiczne_autogen/mocs_compilation.s"
	@echo "... glowneokno.o"
	@echo "... glowneokno.i"
	@echo "... glowneokno.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... oknoczujnikow.o"
	@echo "... oknoczujnikow.i"
	@echo "... oknoczujnikow.s"
	@echo "... oknostatusowe.o"
	@echo "... oknostatusowe.i"
	@echo "... oknostatusowe.s"
	@echo "... stanczujnika.o"
	@echo "... stanczujnika.i"
	@echo "... stanczujnika.s"
	@echo "... ustawieniadozownikaokno.o"
	@echo "... ustawieniadozownikaokno.i"
	@echo "... ustawieniadozownikaokno.s"
	@echo "... ustawieniasygnalowokno.o"
	@echo "... ustawieniasygnalowokno.i"
	@echo "... ustawieniasygnalowokno.s"
	@echo "... widokczujnika.o"
	@echo "... widokczujnika.i"
	@echo "... widokczujnika.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

